[workspace]
authors = ["Shekar V <vshekar1@bnl.gov>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
lab = "jupyter-lab"
start = [{ task = "lab" }]

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.5,<5"
