[workspace]
authors = ["Shekar V <vshekar1@bnl.gov>"]
channels = ["conda-forge"]
name = "cuda-exercise"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.1,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = "*"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = "*"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]


