[workspace]
authors = ["Shekar V <vshekar1@bnl.gov>"]
channels = ["conda-forge"]
name = "cuda-example"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda-version = "12.9.*"

[system-requirements]
cuda = "12"

[target.linux-64.dependencies]
cuda = ">=12.9.1,<13"
pytorch-gpu = ">=2.7.1,<3"

[target.osx-arm64.dependencies]
pytorch = ">=2.8.0,<3"
